name: Hephaestus
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize, ready_for_review]
    paths:
      - 'packages/**/PKGBUILD'
      
jobs:
   validate-and-build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can access the target branch

      - name: Fetch main branch
        run: |
          # Replace 'main' with your default branch name if necessary
          git fetch origin main

      - name: Check if PR involves PKGBUILD file
        id: check_pkgbuild
        run: |
          # Check if PKGBUILD file is part of the changes in the PR
          if git diff --name-only --diff-filter=ACMRT origin/main...${{ github.event.pull_request.head.sha }} | grep -q 'PKGBUILD'; then
            echo "PKGBUILD file is involved in the PR."
            echo "should_label=true" >> $GITHUB_ENV
          else
            echo "should_label=false" >> $GITHUB_ENV
          fi

      - name: Label PR if PKGBUILD file is involved
        if: env.should_label == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: '1.has: package'

      - name: Directory validation
        id: dir_validation
        run: |
          PKGBUILD_PATH=$(find . -type f -name "PKGBUILD")
          TOOL_NAME=$(basename $(dirname $PKGBUILD_PATH))

          if [[ $TOOL_NAME == python* ]]; then
            EXPECTED_DIR="packages/libs/python"
          elif [[ $TOOL_NAME == perl* ]]; then
            EXPECTED_DIR="packages/libs/perl"
          else
            EXPECTED_DIR="packages/pentesting"
          fi

          if [[ ! $PKGBUILD_PATH == ./$EXPECTED_DIR/* ]]; then
            echo "Error: $TOOL_NAME should be in $EXPECTED_DIR but found in $(dirname $PKGBUILD_PATH)."
            exit 1
          fi

      - name: Run Podman Container to Build PKGBUILD
        run: |
          PKGBUILD_DIR=$(dirname $(find . -type f -name "PKGBUILD"))
          podman run --rm -v "${GITHUB_WORKSPACE}/${PKGBUILD_DIR}:/build" docker.io/athenaos/hephaestus
