name: Hephaestus
on:
  pull_request_target:
    types: [opened, reopened, edited, ready_for_review]
    paths:
      - 'packages/**/PKGBUILD'

jobs:
   validate-and-build:
    name: Build Package
    if: github.repository_owner == 'Athena-OS' && startsWith('request:new-pkg', github.event.label.name)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PKGBUILD file is modified
        id: check_pkgbuild
        run: |
          # Check if PKGBUILD file is changed in the PR
          if git diff --name-only origin/main...${{ github.event.pull_request.head.sha }} | grep -q '^PKGBUILD$'; then
            echo "PKGBUILD file is modified."
            echo "should_label=true" >> $GITHUB_ENV
          else
            echo "should_label=false" >> $GITHUB_ENV
          fi

      - name: Label PR if PKGBUILD file is modified
        if: env.should_label == 'true' # Run this step only if PKGBUILD is modified
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: '1.has: package'

      - name: Directory validation
        id: dir_validation
        run: |
          PKGBUILD_PATH=$(find . -type f -name "PKGBUILD")
          TOOL_NAME=$(basename $(dirname $PKGBUILD_PATH))

          if [[ $TOOL_NAME == python* ]]; then
            EXPECTED_DIR="packages/libs/python"
          elif [[ $TOOL_NAME == perl* ]]; then
            EXPECTED_DIR="packages/libs/perl"
          else
            EXPECTED_DIR="packages/pentesting"
          fi

          if [[ ! $PKGBUILD_PATH == ./$EXPECTED_DIR/* ]]; then
            echo "Error: $TOOL_NAME should be in $EXPECTED_DIR but found in $(dirname $PKGBUILD_PATH)."
            exit 1
          fi

      - name: Run Podman Container to Build PKGBUILD
        run: |
          PKGBUILD_DIR=$(dirname $(find . -type f -name "PKGBUILD"))
          podman run --rm -v "${GITHUB_WORKSPACE}/${PKGBUILD_DIR}:/build" docker.io/athenaos/hephaestus
