name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    types: [opened, reopened, edited, synchronize, ready_for_review]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Build Package
         with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0  # Fetch all history so we can access the target branch
         
       - name: Test
         run: |
           CHANGED_FILES=($(git diff --name-only --diff-filter=d $GITHUB_SHA HEAD))
           echo "Ciao $GITHUB_SHA $CHANGED_FILES"
           for FILE in $CHANGED_FILES; do
              if [[ $(basename $FILE) == "PKGBUILD" ]]; then
                docker build -t builder -f Dockerfile-test $(dirname $FILE)
                docker run --rm builder
              fi
           done
  pkgcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pkgcheck-arch --user
      - name: Check Styling
        run: |
           COMMIT_RANGE=($(git diff --name-only --diff-filter=d $(git log -2 --format=%H | tr '\n' ' ')))
           CHANGED_FILES=($(git diff --name-only $COMMIT_RANGE))
           for FILE in $CHANGED_FILES; do
              if [[ $(basename $FILE) == "PKGBUILD" ]]; then
                pkgcheck $FILE
              fi
           done
