name: Vulcano
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    types: [opened, reopened, edited, synchronize, ready_for_review]
    paths:
      - 'packages/**/PKGBUILD'

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - name: Labeling
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: '1.has: package'
