name: Vulcano

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    types: [opened, reopened, edited, synchronize, ready_for_review]
    paths:
      - 'packages/**/PKGBUILD'

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - name: Labeling
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: '1.has: package'

  pkgcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pkgcheck-arch

      - name: Check Styling
        run: |
          CHANGED_FILES=($(git diff --name-only --diff-filter=ACMRT origin/main...${{ github.event.pull_request.head.sha }} | tr '\n' ' '))
          for FILE in "${CHANGED_FILES[@]}"; do
            if [[ $(basename "$FILE") == "PKGBUILD" ]]; then
              echo "Validating $FILE..."
              pkgcheck "$FILE"
            fi
          done

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Package
        run: |
          CHANGED_FILES=($(git diff --name-only --diff-filter=ACMRT origin/main...${{ github.event.pull_request.head.sha }} | tr '\n' ' '))
          for FILE in "${CHANGED_FILES[@]}"; do
            if [[ $(basename "$FILE") == "PKGBUILD" ]]; then
              echo "Building $FILE..."
              docker run --rm -v "${GITHUB_WORKSPACE}/$(dirname "$FILE"):/src" docker.io/athenaos/vulcano
            fi
          done
